### ISSUE TITLE
Bookmarking function does not work

### ISSUE THREAD

**Issue by MinaCora** [frrahat/Quran-For-My-Android#10] opened 2015-05-09 06:11 UTC
Assalamu 'Alaikum my brother. 

I have found a bug in a function you have implemented in rel. 1.3. which I am not making use of - but I would like to mention - because other people could need it. 
My smartphone as Android 5.0 Lollipop as operating system and when I have a verse displayed on the screen and press the bookmark button the app crashes. 

If you can't reproduce this problem on your device then please forget what I wrote. The operating system on my device is a custom version. Maybe the bug could be related to it. 
Although it works flawlessly in all other apps - but it could be the root cause for the bug. 

May Allah take care of you!

**Comment by frrahat** [comment] 2015-05-09 12:18
Walaikum Assalam Wa Rahmatullah.
I didn't get anything like this with the devices I have checked the app. May be, your assumption is correct or there is a problem with storage system. Do you have an external storage with your device?

**Comment by frrahat** [comment] 2015-05-09 18:22
Here is a new update: https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.3.1
I highly expect that it will solve the problem, if the problem was for storage location, but I am not sure.

**Comment by MinaCora** [comment] 2015-05-10 08:57
Assalamu 'Alaikum my brother. 
Thank you for taking care!
I have downloaded the new app onto my phone and unfortunately the bookmarking function led again to an app crash. 
Then I have downloaded it also to another phone which is also running on Android 5.0 - and unfortunately this one shows also the same behaviour. 
Both devices have external storage. 
But it could be also related to the customized ROM's on the devices. I can confirm that all other installed apps work fine.
If you need further information please let me know. 
I feel honor in helping you.

**Comment by MinaCora** [comment] 2015-05-10 09:09
I have installed it also on a device with Android 4.0 and when pressing the bookmark button it sayed "Couldn't get target ayah. Try in verse mode". When pressing again it crashed. 
Now when I start the app on the device and press the button it crashes without the mentioned text. 
This device is on stock rom. It has also external storage (separate micro SD card). 
Hope this information helps you in finding the bug.

**Comment by frrahat** [comment] 2015-05-10 13:40
Jazakallahu khairan for your kind interest and patience. Alhamdulillah! I think, I have found out what is the cause of this problem.

At first I thought, there would be a problem with the storage system, or your device was somewhat different. I rechecked my code, but wasn't able to find which was creating the difference. But now Alhamdulillah, I think I have found out the missing block. That is with the **_Word By Word**_ text mode for which I forgot to be careful of and this is the reason the bookmarking should crash on all devices!

I think, you are using Word By Word Text as the primary text, so you have faced this problem, aren't you?

Jazakallahu khairan for pointing out this bug. Insha Allah, I will give a new update with the fix of this problem.

**Comment by MinaCora** [comment] 2015-05-10 18:01
Wa Antum fa Jazâkumu-Allâhu khayran!
Yes indeed I am using the unchanged words of Allah first. In addition I am reading the transliteration and the English translation. In addition the Turkish and German translation whenever I do not understand the meaning or to see how other translations have translated from the original in Arabic. 
This is why I love your app because it offers me the possibility to do this. 
And indeed this is a nice forum here which makes me possible to say thank you personally. 
Thank your very much for this fantastic app!
May Allah take care of you and support you.

**Comment by frrahat** [comment] 2015-05-10 19:50
All praises be to Allah, He gave me the chance to build this app. Wa ma taufiqi illa billah.

Now here is a new one. If you find time, please check this release: https://github.com/frrahat/Quran-For-My-Android/releases/tag/1.4.0

Jazakallahu khairan for your continuous feedback.

**Comment by MinaCora** [comment] 2015-05-14 08:30
Wa Antum fa Jazâkumu-Allâhu khayran.
Sorry for my late response I was on a business trip the last days and had no time to check this forum. 
You are right, all success is by Allah.
I have prayed that your success continues. 
I have installed the newest build and tested it. 
It works fine!
Thank you very much. 
May Allah protect and guide you.

**Comment by frrahat** [comment] 2015-05-14 10:01
Thanks for your response. May Allah also protect and guide you.
As the bug is fixed, I'm closing this issue.

**Closed as completed by frrahat** 2015-05-14 10:01 UTC
